# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3d76c7d3a2639f989ec6aa968b9d6d52"
name = "otoh"
handle = "otoh"
application_url = "https://down-characterization-disc-disclaimer.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-47141311.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://down-characterization-disc-disclaimer.trycloudflare.com/auth/callback",
  "https://down-characterization-disc-disclaimer.trycloudflare.com/auth/shopify/callback",
  "https://down-characterization-disc-disclaimer.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
